run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - gofmt
    - goimports
    - gosec
    - misspell
    - lll
    - unparam

linters-settings:
  goimports:
    local-prefixes: github.com/victoralfred/um_sys
  lll:
    line-length: 120

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - lll