run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - bin
    - .git
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_mock\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
      
  gocyclo:
    min-complexity: 15
    
  dupl:
    threshold: 100
    
  goconst:
    min-len: 3
    min-occurrences: 3
    
  misspell:
    locale: US
    
  unused:
    check-exported: true
    
  unparam:
    check-exported: true
    
  nakedret:
    max-func-lines: 30
    
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
    
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - wrapperFunc
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - importShadow
      
  funlen:
    lines: 100
    statements: 50
    
  gosec:
    excludes:
      - G104 # Audit errors not checked
      - G204 # Subprocess launched with variable
      
  lll:
    line-length: 120
    
  maligned:
    suggest-new: true
    
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
          - assign
        ignored-numbers: 0,1,2,3,4,5,10,24,60,100,200,400,404,500,1000,1024
        ignored-functions: make,len,cap,strconv.*
        
  gomodguard:
    allowed:
      modules:
        - github.com/gin-gonic/gin
        - github.com/lib/pq
        - github.com/go-redis/redis
        - github.com/golang-jwt/jwt
        - github.com/stretchr/testify
        - github.com/google/uuid
        - github.com/joho/godotenv
        - golang.org/x/crypto
        - github.com/golang-migrate/migrate
        - gopkg.in/natefinch/lumberjack.v2
    blocked:
      modules:
        - github.com/pkg/errors:
            recommendations:
              - fmt
              - errors
        - github.com/gorilla/mux:
            recommendations:
              - github.com/gin-gonic/gin

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gomnd
        - funlen
        
    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "
      
    # Exclude known linter issues
    - path: internal/adapters/
      text: "don't use an underscore in package name"
      
    # Exclude shadow checking in test files
    - path: _test\.go
      text: "shadow: declaration of"
      
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
  case-sensitive: false